# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: spider

on:
  push:
    branches: [ master ]

  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '1 21 * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Node启动
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: |
        npm install 
        node index.js
